# Generated by Django 2.1.3 on 2018-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftrota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrotainfo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
