# Generated by Django 2.1.3 on 2018-11-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftrota', '0003_auto_20181125_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrotainfo',
            name='last_name',
        ),
    ]
