# Generated by Django 2.1.3 on 2018-11-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftrota', '0005_auto_20181127_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrotainfo',
            name='shift',
            field=models.CharField(choices=[('shift1', 'Morning'), ('shift2', 'General'), ('shift3', 'Afternoon'), ('shift4', 'Night')], max_length=50),
        ),
    ]
