# Generated by Django 2.1.3 on 2018-11-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftrota', '0006_auto_20181127_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftrotainfo',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='shiftrotainfo',
            old_name='first_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='shiftrotainfo',
            old_name='shift',
            new_name='Shift',
        ),
    ]
